### ISSUE TITLE
No binary for windows and macos

### ISSUE THREAD

**Issue by rexdf** [eddiejessup/Transcrypt#1]
No binary for windows and no readme

**Comment by rexdf** [comment]
I have complied a 64 version with some bat file. Can I make a pull request with supports both 32 and 64 bit version?

**Comment by eddiejessup** [comment]
Sure go ahead, as long as you've tested it to your own satisfaction, as I
don't have access to a Windows machine. Thanks!

**Comment by rexdf** [comment]
Done. Both 32 and 64 Windows version 3083 tested.

**Comment by rexdf** [comment]
[Windows 32 bit version](https://github.com/rexdf/Crypto_Python_Windows/archive/release.zip) and [Windows 64 bit version](https://github.com/rexdf/Crypto_Python_Windows/archive/release_64.zip)

**Comment by eddiejessup** [comment]
I'm pretty busy at the moment so it might take a while for me to merge
these in manually. How do you feel about merging them yourself then
submitting a pull request?

**Comment by rexdf** [comment]
I have no idea about how to seperate the version. Some file name on different platform. I'll try on it these two days. Maybe I can learn something from [Emmet](https://packagecontrol.io/packages/Emmet), it has pre-build module and support all platform.

**Comment by eddiejessup** [comment]
Yeah I don't know how to do that either. Looks like emmet downloads the
correct binary at install-time, that could work. Sorry I'll try to have a
proper look at it in a couple of weeks when I'm less busy.

**Comment by rexdf** [comment]
Now static binary file. `block_template.c` need to be adapted according to platform name.

``` c
struct PyModuleDef moduledef
Py_InitModule
PyImport_ImportModule
```

I cannot load library with relative path. It's not the ideal way, but it works.
