### ISSUE TITLE
Stopped working...

### ISSUE THREAD

**Issue by ajitam** [eddiejessup/Transcrypt#13]
Is it just me or this plugin stopped working?

`Encrypt` and `Decrypt` options are "Grayed out"

![screen shot 2018-05-28 at 12 49 31](https://user-images.githubusercontent.com/672661/40611304-176ac1f4-6276-11e8-8212-b0b43f6f6699.png)

```
macOS 10.13.4
ST 3.1.1 (3176)
```

**Comment by ajitam** [comment]
anything?

**Comment by eddiejessup** [comment]
Hey, sorry for the late reply. I forgot to amend the context menu settings when I pushed the last version; I think the logic was all working but the context menu had the wrong command references. I've pushed a new version; package control should pick it up and upgrade sometime soon.

Let me know if this is resolved :)

Sorry again for my bad feedback, I've been a bit of a busy bee lately.

**Comment by ajitam** [comment]
Works 👍 

pheeew - had some secrets encrypted :)

**Comment by eddiejessup** [comment]
@ajitam ah I hadn't thought of this possibility. Man, that's a lot of pressure to maintain this thing now!

**Comment by ajitam** [comment]
yep, keep up the good work

(nah, I would just just some other external script - no pressure)
