### ISSUE TITLE
Which is the openssl command equivalent to decrypt the encypted output of Transcrypt?

### ISSUE THREAD

**Issue by brx75** [eddiejessup/Transcrypt#14]
Hi,
I'ld like to have an alternative way to decrypt the data just in case I'll be on a pc without Sublime Text or without a way to install this extension.
For example, with the "original" Crypto extension, I'ld be able to decrypt the text block by using
```
$ openssl enc -d -aes128 -bsae64 -in INFILE
```

What could be the equivalent openssl command for Transcrypt?

Regards, Brx

**Comment by zayne1** [comment]
Any feedback possible on this?

**Comment by eddiejessup** [comment]
Hey, sorry for not replying before. I can point you to the core functions that do the transcryption,

[en/decrypt wrapper](https://github.com/eddiejessup/Transcrypt/blob/1a5894a2c355e1b88626a2b195e132bd7e701981/Transcrypt.py#L116)
[encryption](https://github.com/eddiejessup/Transcrypt/blob/1a5894a2c355e1b88626a2b195e132bd7e701981/Transcrypt.py#L106)
[decryption](https://github.com/eddiejessup/Transcrypt/blob/1a5894a2c355e1b88626a2b195e132bd7e701981/Transcrypt.py#L94)

There are things like padding of the input, and padding of the key, which I guess you'd want to mimic through the `openssl` call. I'm not sure whether openssl has options to do those things. It does seem like those are reasonably common behaviours?

Have you tried running your above command, to see whether it works? It doesn't sound like it's far from what the plugin is doing.

I'll try to have a look myself this evening.

**Comment by eddiejessup** [comment]
Honestly, at this point I think I should archive this plugin, if it stays in its current state. I think vendoring cryptography code in a text editor plugin is a pretty bad idea, and the approach of the original crypto plugin of having an external dependency to do the crypto bits, like calling `openssl`, is a much better way to go.

Is there some functionality in this plugin that you can't easily get elsewhere? If so, maybe we could work on replacing the vendored code with calls to `openssl`. I guess this would solve your current issue, and also make me feel happier keeping the plugin available. I don't think it would be a lot of work, maybe a handful of hours.

How does this sound?

**Comment by alex-hunsley-nl** [comment]
+1 for this question, I have encrypted text and the package isn't working for me now.

UPDATE: I was using sublime text 4. So then I downloaded ST3 from website and found out that transcrypt still works in that version.

**Comment by eddiejessup** [comment]
Can you try running this script with your encoded file and password, then running the openssl command it outputs, to see if it works?

https://gist.github.com/eddiejessup/8de79e939b977e24491c9f26690c4c90

**Comment by eddiejessup** [comment]
From testing with someone else I think this works, so closing. Please reopen if I'm wrong
