### ISSUE TITLE
warning: mnemonic t not found in menu caption Tools

### ISSUE THREAD

**Issue by rb0w** [eddiejessup/Transcrypt#4]
Hi. Including the Transcrypt plugin in ST3 (3083) causes the above warning.
It also disabled "Alt-t", the short-cut key for Tools in the main menu. 
Is there any quick fix to stop this behaviour?

**Comment by rb0w** [comment]
Solved. 
In file _Main.sublime-menu_, change 

```
"mnemonic": "t" 
```

->

```
"mnemonic": "T"
```

**Comment by eddiejessup** [comment]
Hi! Thanks for letting me know about a possible problem. Is a fix needed? You think I should make the change you mention? I'm just confused because you closed the issue, which implies no further changes are needed.

**Comment by rb0w** [comment]
You're welcome.  I could not be sure if it's an one-off and doesn't require any change, or it is showing up in other systems as well.  So I simply left it as a record.

**Comment by rb0w** [comment]
On closer inspection, the change from "t" to "T" is likely necessary since the Tool shortcut key has to match that of ST3.  Sorry for the confusion earlier.  I should have kicked the ball further, :).  Don't think re-opening this issue is necessary though.

**Comment by eddiejessup** [comment]
I can't actually see where these mnemonics live in ST3, but I'm going to blindly make the change you suggest, and you can hopefully let me know if it works?

If you could also point me to where the mnemonics are listed, so I can understand what I've done, that would be great, but it's not a big deal.

**Comment by rb0w** [comment]
Thank you for the plugin and fix. Not showing this warning now. Less debug chatter :+1:

The mnemonics for the Main menu of ST3 (v3083) can be found in _Main.sublime-menu_.   This file in zipped inside 

```
[ST3 install path]/Packages/Default.sublime-package
```

I'm puzzled by the fact that ST3 is responding to "alt+t" for Tools although "mnemonic":"T" is coded (line 707 in _Main.sublime-menu_).   Don't you think it's a little unproductive that every menu for plugins has to duplicate the mnemonics?   BTW, I'm using ST3 on Linux.  Wonder if this has to do with case-sensitivity, which may not be an issue on a Windows system?  Not knowing all the anwsers keeps me alive. Haha.

**Comment by eddiejessup** [comment]
Thanks for letting me know where they are. I absolutely am puzzled at the mnemonic duplication, so yucky. I would have presumed the menu was created by merging all the .sublime-menu JSON objects progressively into the default one, and I'd expect un-specified fields to be just left at the default value. Hm.

I'm not even sure how to do this toolbar keyboard shortcuts thing on OS X, which is why I got you to check for the fix, so I don't know about the case sensitivity thing. But sounds reasonable. I'll stick you on the contributors list, so now you've another reason to live.

**Comment by BransonGitomeh** [comment]
For some reason in latest version of sublime this is still appearing in the console.

**Comment by easternwawoman** [comment]
8/30/2018 and getting the mnemonic f not found warning in console.

**Comment by claudiokc** [comment]
I'm using ST4 and the warning still there
