### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'new'

### ISSUE THREAD

**Issue by zr0sum** [eddiejessup/Transcrypt#5]
Windows 10 x64, When trying to encrypt a file using Sublime Text 3, Build 3083:

```
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\Transcrypt\Transcrypt.py", line 209, in run
    result = crypt(password, data, enc)
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\Transcrypt\Transcrypt.py", line 168, in crypt
    secret = AES.new(key_b_round)
AttributeError: 'NoneType' object has no attribute 'new'
```

**Comment by eddiejessup** [comment]
Hi and thanks for letting me know! Probably something's gone wrong when extracting the binary files or importing them. Maybe the win64 binary files don't work on Windows 10. Hopefully I can get a chance to look into this further in the next few days.

**Comment by eddiejessup** [comment]
If it is indeed a Windows 10 binary issue, then I should be able to solve it by just bundling yet one more set of binaries (what I do is unzip the correct set of binary files for the platform into a directory when the plugin is installed. It's ugly). But I'd need someone with access to Windows 10 x64 to compile the files.

I don't really know how Windows works for anything technical, but if you can do whatever is needed to run a `setup.py` file, you could run the file in the dev branch, and send me over the binaries it generates? It would be even better if you tested that this fixes the issue first (I can tell you how to do this).
