### ISSUE TITLE
[Question] How Transcrypt protect my private data?

### ISSUE THREAD

**Issue by Kristinita** [eddiejessup/Transcrypt#9]
### Briefly

It would be nice, if you write in README.MD, how Transcrypt to work.

### Detail

Users can afraid for security of my private information. For example, I encrypt my text use Transcrypt and my enemy got encrypted file but he not knows my password.

• Where is stored my Transcrypt password?
• May my enemy discover my password, if he has all files of my Sublime Text?

Thanks.

**Comment by alexhunsley** [comment]
Your Transcrypt password is stored only in your head. For Transcrypt to (knowingly) store your actual password anywhere would completely defeat the purpose of encryption.

Note that this means if you forget your password, you have no hope of decrypting your data.

Don't allow anyone to copy your head.

Disclaimer: I didn't write Transcrypt. But as a computer professional, I would be very surprised if the above was not true.

Transcrypt uses AES encryption (https://en.wikipedia.org/wiki/Advanced_Encryption_Standard).
If you want to choose a good password, I'd suggest 22 characters chosen completely randomly by a password generator like 1Password.

https://crypto.stackexchange.com/questions/42538/is-password-based-aes-encryption-secure-at-all

**Comment by eddiejessup** [comment]
Yes, what @alexhunsley said. Hope that clears things up @Kristinita!
